version: 2
jobs:
  build:
    working_directory: ~/ngrx-history-lib
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: ngrx-history-lib-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ngrx-history-lib-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- ngrx-history --browsers=ChromeHeadless
      - run: npm run upload:coverage
